# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Class Random_walk
#' @name Random_walk
#' @description drifted random walk class
#' @export Random_walk
NULL

